### ISSUE TITLE
Questions about the output attributes

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/dba_qcfilter#1]
Up to now, the behaviour of `dba_qcfilter` is:

* If preserve option is false:
  * if the data is valid, remove all attributes and keep it
  * if the data is invalid, discard it
* If preserve option is true:
  * if the data is valid, remove all attributes and keep it
  * if the data is invalid, remove all attributes and set B33007=0

Shouldn't we set B33007=100 when data is valid? Otherwise, we can't discriminate between an unchecked data without flags and a valid data that passed the QC.

Moreover, from Pellegrini's report:

> Pertanto ogni dato e' controllato nelle 3 flag di qualità presenti, e viene valutata la somma risultante di tot:
> • se tot risulta inferiore a -1, il dato e' invalidato (B33007=0)
> • se tot risulta maggiore od uguale a -1, il dato e' valido (B33007=1)

(1 should be 100, because B33007 is defined as `PERCENT CONFIDENCE (%)`)

**Comment by edigiacomo** [comment]
Update: the algorithm seems more complex (sorry, you know that I'm not very proficient in Fortran):

* If preserve option is false: 
  * if the data is valid, remove all attributes __that are involved in QC__ and keep it 
  * if the data is invalid, discard it
* If preserve option is true: 
  * if the data is valid, remove all attributes __that are involved in QC__ and keep the it
  * if the data is invalid, remove all attributes (__those that are not involved in QC too__), set B33007=0 and keep it

The algorithm is inferred from the results of the Fortran version of dba_qcfilter. 

```
$ dbamsg dump --interpreted generic.bufr
#0[0] generic message, 43.12345,12.12345, dt: 2020-01-01T01:01:01, 2 contexts:
Level -,-,-,-, tr -,-,-,
001194 Report mnemonic(CCITTIA5): test
004001 YEAR(YEAR): 2020
004002 MONTH(MONTH): 1
004003 DAY(DAY): 1
004004 HOUR(HOUR): 1
004005 MINUTE(MINUTE): 1
004006 SECOND(SECOND): 1
005001 LATITUDE (HIGH ACCURACY)(DEGREE): 43.12345
006001 LONGITUDE (HIGH ACCURACY)(DEGREE): 12.12345
Level 103,2000,-,-, tr 254,0,0
012101 TEMPERATURE/DRY-BULB TEMPERATURE(K): 0.00
           033036 NOMINAL CONFIDENCE THRESHOLD(%): 50
           033192 Climatological and consistency check(%): 50
#1[0] generic message, 43.12345,12.12345, dt: 2020-01-01T01:01:01, 2 contexts:
Level -,-,-,-, tr -,-,-,
001194 Report mnemonic(CCITTIA5): test
004001 YEAR(YEAR): 2020
004002 MONTH(MONTH): 1
004003 DAY(DAY): 1
004004 HOUR(HOUR): 1
004005 MINUTE(MINUTE): 1
004006 SECOND(SECOND): 1
005001 LATITUDE (HIGH ACCURACY)(DEGREE): 43.12345
006001 LONGITUDE (HIGH ACCURACY)(DEGREE): 12.12345
Level 103,2000,-,-, tr 254,0,0
012101 TEMPERATURE/DRY-BULB TEMPERATURE(K): 0.00
           033036 NOMINAL CONFIDENCE THRESHOLD(%): 50
           033192 Climatological and consistency check(%): 50
           033196 Data has been invalidated(CODE TABLE): 1
```
The first message is valid and only B33192 (i.e. the one involved in QC) is stripped:

```
$ cat generic.bufr | dba_qcfilter | dbamsg dump --interpreted
#0[0] generic message, 43.12345,12.12345, dt: 2020-01-01T01:01:01, 2 contexts:
Level -,-,-,-, tr -,-,-,
001194 Report mnemonic(CCITTIA5): test
004001 YEAR(YEAR): 2020
004002 MONTH(MONTH): 1
004003 DAY(DAY): 1
004004 HOUR(HOUR): 1
004005 MINUTE(MINUTE): 1
004006 SECOND(SECOND): 1
005001 LATITUDE (HIGH ACCURACY)(DEGREE): 43.12345
006001 LONGITUDE (HIGH ACCURACY)(DEGREE): 12.12345
Level 103,2000,-,-, tr 254,0,0
012101 TEMPERATURE/DRY-BULB TEMPERATURE(K): 0.00
           033036 NOMINAL CONFIDENCE THRESHOLD(%): 50
```

With `--preserve` option, you can see above that _all the attributes_ are stripped from the second message and B3307=0 is set.

```
$ cat generic.bufr | dba_qcfilter --preserve | dbamsg dump --interpreted
#0[0] generic message, 43.12345,12.12345, dt: 2020-01-01T01:01:01, 2 contexts:
Level -,-,-,-, tr -,-,-,
001194 Report mnemonic(CCITTIA5): test
004001 YEAR(YEAR): 2020
004002 MONTH(MONTH): 1
004003 DAY(DAY): 1
004004 HOUR(HOUR): 1
004005 MINUTE(MINUTE): 1
004006 SECOND(SECOND): 1
005001 LATITUDE (HIGH ACCURACY)(DEGREE): 43.12345
006001 LONGITUDE (HIGH ACCURACY)(DEGREE): 12.12345
Level 103,2000,-,-, tr 254,0,0
012101 TEMPERATURE/DRY-BULB TEMPERATURE(K): 0.00
           033036 NOMINAL CONFIDENCE THRESHOLD(%): 50
#1[0] generic message, 43.12345,12.12345, dt: 2020-01-01T01:01:01, 2 contexts:
Level -,-,-,-, tr -,-,-,
001194 Report mnemonic(CCITTIA5): test
004001 YEAR(YEAR): 2020
004002 MONTH(MONTH): 1
004003 DAY(DAY): 1
004004 HOUR(HOUR): 1
004005 MINUTE(MINUTE): 1
004006 SECOND(SECOND): 1
005001 LATITUDE (HIGH ACCURACY)(DEGREE): 43.12345
006001 LONGITUDE (HIGH ACCURACY)(DEGREE): 12.12345
Level 103,2000,-,-, tr 254,0,0
012101 TEMPERATURE/DRY-BULB TEMPERATURE(K): 0.00
           033007 PER CENT CONFIDENCE(%): 0
```

**Comment by pat1** [comment]
intanto do i riferimenti per la vera documentazione (e non altre derivate che sono più imprecise)
https://github.com/ARPA-SIMC/libsim/blob/master/qc/modqc_peel_util_include.F90#L42
https://github.com/ARPA-SIMC/libsim/blob/master/bin/dba_qcfilter.F03#L45

**Comment by pat1** [comment]
per quanto riguarda impostare B33007=100 la faccenda è complessa:
avendo stabilito quali siano le condizioni per avere un dato errato non sono automaticamente stabilite le restanti condizioni, ossia se non è 0 non è automaticamente 100
condivido la necessità di farlo, ma bisogna stabilire quali siano gli stati necessari e sufficienti per definire confidenze diverse da 0

**Comment by edigiacomo** [comment]
> intanto do i riferimenti per la vera documentazione (e non altre derivate che sono più imprecise)
> https://github.com/ARPA-SIMC/libsim/blob/master/qc/modqc_peel_util_include.F90#L42
> https://github.com/ARPA-SIMC/libsim/blob/master/bin/dba_qcfilter.F03#L45

Grazie, avevo già guardato quelle righe e direi che al momento funziona esattamente così anche il nuovo dba_qcfilter.

> condivido la necessità di farlo, ma bisogna stabilire quali siano gli stati necessari e sufficienti per definire confidenze diverse da 0

Quindi per ora faccio come si è sempre fatto, i.e. B33007 viene impostato a zero solo se il dato è non valido ed è usata l'opzione `--preverse`.

Mi rimane il dubbio di cosa fare con gli altri attributi, vedi commento https://github.com/ARPA-SIMC/dba_qcfilter/issues/1#issuecomment-600480505, mi pare che questo non venga esplicitato nei link che mi hai passato. Per ora questo problema al SIMC non ce l'abbiamo perché tanto lavoriamo con dati che usano solo attributi coinvolti nel QC, però sarebbe da chiarire. Fino a che non è chiarito, dichiaro indefinito il comportamento di dba_qcfilter sugli attributi non coinvolti nel QC.

**Comment by pat1** [comment]
"Mi rimane il dubbio di cosa fare con gli altri attributi"
io credo sia corretto rimuovere solo gli attributi coinvolti nel QC
il differente funzionamento trovato nella libsim credo sia dovuto solo a una scorciatoia software/tentativo di ottimizzazione apro una issue per conformare il comportamento
https://github.com/ARPA-SIMC/libsim/issues/81

**Comment by edigiacomo** [comment]
Quindi giusto per essere sicuro, l'attuale algoritmo

> * If preserve option is false:
>   * if the data is valid, remove all attributes **that are involved in QC** and keep it
>   * if the data is invalid, discard it
>
> * If preserve option is true:
>   * if the data is valid, remove all attributes **that are involved in QC** and keep the it
>   * if the data is invalid, remove all attributes (**those that are not involved in QC too**), set B33007=0 and keep it


Deve diventare
* If preserve option is false:
  * if the data is valid, remove all attributes **that are involved in QC** and keep it
  * if the data is invalid, discard it 
* If preserve option is true:   
  * if the data is valid, remove all attributes **that are involved in QC** and keep the it
  * if the data is invalid, remove all attributes *that are involved in QC*, set B33007=0 and keep it

In italico la parte diversa.

**Comment by pat1** [comment]
se pare logico anche a voi io direi di si; la logica a mio parere dovrebbe essere quella di avere una serie di confidenze "private" per l'elaborazione del QC, mentre B33007 è standardizzato per lo scambio dati e quindi per la "sincronizzazione" tra centri
senza --preserve si va verso applicazioni che devono usare solo dati buoni
con    --preserve  si va verso sistemi di archiviazione / scambio dati

**Comment by edigiacomo** [comment]
Attendo risposta di @dcesari per implementare il comportamento.

Per l'uso di B33007 quando il dato è buono, invece, apro altra issue (essendo indipendente da questa, possiamo affrontarla a parte).

**Comment by edigiacomo** [comment]
@dcesari @pat1 alla luce di quanto è cambiato in tre anni, vi chiedo un feedback per implementare o meno il comportamento descritto in questa issue.

**Comment by edigiacomo** [comment]
@dcesari @pat1 vi pingo nuovamente sull'argomento. Visto che è passato parecchio tempo, può anche essere che il comportamento attuale è invece accettabile e in tal caso potete chiudere la issue.

**Comment by dcesari** [comment]
Ah, scusa, mi deve essere sfuggita, mi pare logico così come proposto.
